### ISSUE TITLE
Gradle repository support

### ISSUE THREAD

**Issue by dmitrikudrenko** [thebnich/FloatingHintEditText#1]
Can you make support of import your project from maven-central?

**Comment by thebnich** [comment]
Sure, I'll try to get this deployed in the next week or so.

**Comment by vjnrv** [comment]
+1

**Comment by andreas-** [comment]
any updates on the maven upload?

**Comment by andreas-** [comment]
and someone else took care of it
https://github.com/IanGClifton/AndroidFloatLabel

**Comment by dmitrikudrenko** [comment]
Use [TextInputLayout](https://developer.android.com/reference/android/support/design/widget/TextInputLayout.html) instead of custom libraries
